apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/app1
images:
  - name: PLACEHOLDER_IMAGE
    newName: docker.io/archcra/app1
    newTag: app1-developer-64
